# Generated by Django 4.1.5 on 2024-02-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_stands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookiestand',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
